version: "3.2"

services:

### OMS-STATIC        #######################################

    oms-static:
        build:
          context: ./$PATH_OMS_STATIC/oms-static/
          dockerfile: ./Dockerfile.dev
        image: aegee/oms-static:dev
        restart: always
        volumes:
            - type: bind
              source: ./$PATH_OMS_STATIC/../src/
              target: /usr/app/src
            - type: bind
              source: ./$PATH_OMS_STATIC/../logs/
              target: /usr/app/logs
        labels:
          - "traefik.backend=oms-static"
          - "traefik.port=80"
          - "traefik.enable=true"
          - "traefik.frontend.rule=PathPrefix: /discounts"
          - "traefik.frontend.priority=20"
          - "registry.description=The static service, serving static web pages"
networks:
  default:
    external:
      name: OMS
